// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $CardSection from "./islands/CardSection.tsx";
import * as $CollapsibleCard from "./islands/CollapsibleCard.tsx";
import * as $Footer from "./islands/Footer.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CardSection.tsx": $CardSection,
    "./islands/CollapsibleCard.tsx": $CollapsibleCard,
    "./islands/Footer.tsx": $Footer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
